experiment:
  name: pump
  seed: 42

dataset:
  root: data/axial_flow_pump
  num_classes: 6

graph:
  k_original: 4
  k_positive: 1
  k_negative: 1
  k_optimized: 4

gcva:
  hidden_dim: 256
  latent_dim: 128
  decoder_hidden: 256
  dropout: 0.01
  decoder_dropout: 0.0
  lambda_reg: 0.001
  beta: 1.0
  learning_rate: 0.0075
  epochs: 200

dvtt:
  hidden_dim: 128
  mlp_hidden_dim: 32
  num_self_att_layers: 1
  num_gnn_layers: 3
  nhead: 4
  dropout: 0.01
  learning_rate: 0.001
  epochs: 500
